### PR TITLE
Support fuse rolls, multiple fixes on purple notes etc, add a button to download directly either the chart image or the stats image, more information (subtitle, charter) on the chart graph

### PR DESCRIPTION
**Pull request by 0auBSQ**

### CODE REVIEW

**Comment by 0auBSQ** [comment]
Replaced the bundler by Vite as well (faster build speed), merging it might require extra steps/changes on the github sites side

**Comment by WHMHammer** [comment]
I will work on the changes for the GitHub pages. Thank you for your contribution @0auBSQ !

**Comment by WHMHammer** [comment]
@0auBSQ It looks like you were using `/index.html` as the source for `vite`. However, that file was generated by `webpack` from `src/index.html`. `src/index.html` is the true source.

In my latest commit in my `master` branch, I have moved everything generated by `webpack` to the `webpack-dist` folder to prevent confusion. Would you check your `vite` configs again to make sure `vite` still compiles after this change? Thank you!

**Comment by 0auBSQ** [comment]
Awesome, thank you!
Will give it a look, it should not be very complicated through I am still not used to using bundlers without a set framework

**Pull request merged**
